version: "3"

services:
  jena-fuseki:
    image: stain/jena-fuseki
    ports: 
      - "3030:3030"
    # volumes:
    #   - ./fuseki:/fuseki
    environment:
      - ADMIN_PASSWORD=admin
      - FUSEKI_DATASET_1=resources
  postgres:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
      # - POSTGRES_DB=default_database
    ports:
      - "5432:5432"
    # volumes: 
    #   - ./db:/var/lib/postgresql/dataP