name: Run tests
on:
  schedule:
    - cron: '0 8 * * *' # Run at 8AM UTC.
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Start localnet
        run: |
          make localnet-configure
      - name: Add regen binary to path
        run: echo "$(pwd)/localnet/regen-ledger/build" >> $GITHUB_PATH
      - name: Test localnet config
        run: |
          test $(regen q data resolver 1 --output json | jq -r .resolver.manager) == $(make -sC localnet keys-manager-address)
          test $(regen q data resolver 1 --output json | jq -r .resolver.url) == http://localhost:8000/resource
          test $(regen q bank balances $(make -sC localnet keys-manager-address) -o json | jq '.balances | length') -eq 2
          test $(regen q bank balances $(make -sC localnet keys-service-address) -o json | jq '.balances | length') -eq 0
      - name: Test registering data with resolver
        run: |
          make -C localnet register-resolver
          test $(regen q data resolvers-by-iri regen:13toVgf5aZqSVSeJQv562xkkeoe3rr3bJWZgg1jJfnzPGBtJNpVVakm.rdf --output json | jq -r .resolvers[0].url) == http://localhost:8000/resource
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install deps
        run: poetry install
      - name: Start docker containers
        run: |
          docker compose -f docker/docker-compose.yml up -d
          sleep 10
      - name: Run tests
        env:
          REGEN_CLI_COMMAND: ""
          REGEN_KEYRING_ARGS: "--keyring-backend test --keyring-dir localnet/keys"
        run: |
          poetry run pytest
